apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: token-factory-account
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: token-factory-account
      annotations:
        version: {{.Values.account.image.tag}}
    spec:
      containers:
        - name: token-factory-account
          image: "{{ .Values.account.image.registry }}/{{ .Values.account.image.repository }}:{{.Values.account.image.tag }}"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /liveness
              port: {{.Values.account.service.port}}
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{.Values.account.service.port}}
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 10 
          ports:
            - containerPort: {{.Values.account.service.port}}
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            # - name: MONGO_PWD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongodb
            #       key: mongodb-password
            # - name: MONGO_RS_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongodb
            #       key: mongodb-replica-set-key
            # - name: MONGO_ROOT_PWD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongodb
            #       key: mongodb-root-password
            - name: MONGO_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: accounts
                  key: db_service_name
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: accounts
                  key: db_name
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  name: accounts
                  key: db_user_name  