apiVersion: v1
kind: Service
metadata:
  name: token-factory-registration-service
  labels:
    app: token-factory-registration-service
spec:
  ports:
    - port: {{.Values.registration.service.port}}
      name: http
  selector:
    app: token-factory-registration
  type: {{.Values.registration.service.type}}
