apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: token-factory-ingress
spec:
  tls:
    - hosts:
        - {{.Values.cluster}}.us-east.containers.appdomain.cloud
      secretName: {{.Values.cluster}}
  rules:
    - host: {{.Values.cluster}}.us-east.containers.appdomain.cloud
      http:
        paths:
          - path: /token-factory
            backend:
              serviceName: token-factory-gql-proxy-service
              servicePort: {{.Values.gqlproxy.service.port}}
          - path: /
            backend:
              serviceName: token-factory-ui-service
              servicePort: {{.Values.ui.service.port}}