apiVersion: v1
kind: Service
metadata:
  name: token-factory-account-service
  labels:
    app: token-factory-account-service
spec:
  ports:
    - port: {{.Values.account.service.port}}
      name: http
  selector:
    app: token-factory-account
  type: {{.Values.account.service.type}}
