apiVersion: v1
kind: Service
metadata:
  name: token-factory-ui-service
  labels:
    app: token-factory-ui-service
spec:
  ports:
    - port: {{.Values.ui.service.port}}
      name: http
  selector:
    app: token-factory-ui
  type: {{.Values.ui.service.type}}
