apiVersion: v1
kind: Service
metadata:
  name: token-factory-gql-proxy-service
  labels:
    app: token-factory-gql-proxy-service
spec:
  ports:
    - port: {{.Values.gqlproxy.service.port}}
      name: http
  selector:
    app: token-factory-gql-proxy
  type: {{.Values.gqlproxy.service.type}}
