# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullPolicy: Always

registration:
  image:
    registry: registry.ng.bluemix.net
    repository: blockchain_innovation/token-factory-registration-service
    tag: 1.0.0-28143406d9135db2e55ed7c456e1e4e9236a313a
  service:
    type: ClusterIP
    port: 4000

account:
  image:
    registry: registry.ng.bluemix.net
    repository: blockchain_innovation/token-factory-account-service
    tag: 1.0.0-925cce03f144b43dfd6ac4abe1fc6f8a76337ee9
  service:
    type: ClusterIP
    port: 4001

ui:
  image:
    registry: registry.ng.bluemix.net
    repository: blockchain_innovation/token-factory-ui
    tag: 1.0.0-9f27f4a6f98bf0d5ec1f4750054eedaa0ee5a195
  service:
    type: ClusterIP
    port: 5000

gqlproxy:
  image:
    registry: registry.ng.bluemix.net
    repository: blockchain_innovation/token-factory-gql-proxy
    tag: 1.0.0-6c4b09c4eff785ec420393883221cd40edb7f14e
  service:
    type: ClusterIP
    port: 3001
